require("dotenv").config()
const express = require("express")
const cors = require("cors")
const path = require("path")
const app = express()

const login = require("./routes/login")
const register = require("./routes/register")
const user = require("./routes/user")
const users = require("./routes/users")
const password = require("./routes/password")
const products = require("./routes/products")
const sales = require("./routes/sales")
const salesPeriod = require("./routes/salesPeriod")
const orders = require("./routes/orders")
const dishes = require("./routes/dishes")
const cards = require("./routes/cards")
const tables = require("./routes/tables")
const tableProducts = require("./routes/tableProducts")
const printer = require("./routes/printer")
const cashDrawer = require("./routes/cashDrawer")

app.set("view engine", "ejs")
app.use(express.static(path.join(__dirname, "public")))
app.use(express.urlencoded({ extended: false }))
app.use(express.json())
app.use(cors())

app.use("/login", login)
app.use("/register", register)
app.use("/user", user)
app.use("/users", users)
app.use("/password", password)
app.use("/products", products)
app.use("/sales", sales)
app.use("/sales-period", salesPeriod)
app.use("/orders", orders)
app.use("/dishes", dishes)
app.use("/cards", cards)
app.use("/tables", tables)
app.use("/table-products", tableProducts)
app.use("/print", printer)
app.use("/cash-drawer", cashDrawer)

module.exports = app
